### ISSUE TITLE
Need solution for 'Special Price' in Python language

### ISSUE THREAD

**Issue by RoyalEagle73** [sca-nit-jsr/Code-Quidditch-Solutions-2019#9]
Question can be found here :
[Question](https://www.hackerearth.com/challenges/college/Code-Quidditch/algorithm/f3c66648e2734c7bb68c769d1f37c624/)

**Comment by sanjibansg** [comment]
Added a PR for the solution

**Comment by RoyalEagle73** [comment]
PR was reviewed :100:
